/* 5. Implement an OpenMP program to generate an array of random integers using the single construct. 
	Then use the parallel for directive to compute the square of each element. 
	Display the Thread ID that generates the array and the Thread IDs processing the elements. */
	
#include<stdio.h>
#include<stdlib.h>
#include<omp.h>

int main()
{
    int n;

    printf("Enter size: ");
    scanf("%d", &n);

    int a[n];

    #pragma omp parallel
    {
        #pragma omp single
        {
            printf("Array generated by Thread %d\n", omp_get_thread_num());

            for(int i=0; i<n; i++)
            {
                a[i]=rand()%10+1;
                printf("%d ", a[i]);
			}
            printf("\n");
        } 

        #pragma omp for
        for(int i=0; i<n; i++)
        {
            a[i]=a[i]*a[i];
            printf("Element %d: Thread %d\n", i+1, omp_get_thread_num());
        }
    }

    printf("\nSquared array:\n");
    for(int i=0; i<n; i++)
        printf("%d ", a[i]);

    printf("\n\nTanish Kuvar, 240962540\n");
}
